default: &default
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    username: <%= ENV["LOSTPET101_DATABASE_USERNAME"] %>
    password: <%= ENV["LOSTPET101_DATABASE_PASSWORD"] %>

development:
    <<: *default
    database: Lostpet101_development

test:
    <<: *default
    database: Lostpet101_test

production:
    <<: *default
    database: Lostpet101_production

